
[@inline] let error_NO_ADDUPDATE_ADMIN_ENTRYPOINT = 500n
[@inline] let error_NO_BATCH_REMOVE_ATTRIBUTE_ENTRYPOINT = 501n
[@inline] let error_ATTRIBUTES_DOES_NOT_EXIST = 502n
[@inline] let error_COULD_NOT_UNPACK_ATTRIBUTES = 503n
[@inline] let error_NO_BATCH_UPDATE_ATTRIBUTE_ENTRYPOINT = 504n
[@inline] let error_UNAUTHORIZED_ADMIN_ADDRESS = 505n
[@inline] let error_VIEW_RETURNED_AN_ERROR = 506n
[@inline] let error_NO_REMOVE_UPDATE_ADMIN_ENTRYPOINT = 507n
[@inline] let error_NO_SET_IPFS_HASHES_ENTRYPOINT = 508n
[@inline] let error_YOU_DO_NOT_OWN_THIS_TOKENT = 509n
[@inline] let error_NAME_MUST_BE_BETWEEN_1_AND_30_CHARACTERS = 510n
[@inline] let error_TOKEN_CONTRACT_MUST_HAVE_A_TRANSFER_ENTRYPOINT = 511n
[@inline] let error_INVALID_TO_ADDRESS = 512n
[@inline] let error_FA12_CONTRACT_MUST_HAVE_A_TRANSFER_ENTRYPOINT = 513n
[@inline] let error_TOKEN_CONTRACT_MUST_HAVE_A_BURN_ENTRYPOINT = 514n
[@inline] let error_NFT_CONTRACT_MUST_HAVE_AN_UPDATE_METADATA_WITH_FUNCTION_ENTRYPOINT = 515n
[@inline] let error_NOT_AVATAR_OR_ASSET_TOKEN = 516n











